# Use root/example as user/password credentials
version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linklink_docker_compose
    env_file: 
      - .env
    ports:
      - '3003:3000'
    volumes:
      - ./src:/app/src
# build with image 
    # image: tringuyennek/linglink-system:latest
    # container_name: linklink
    # env_file: 
    #   - .env
    # ports:
    #   - '3003:3000'
    # volumes:
    #   - ./src:/app/src