name: Build LingLink System

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Use Node.js 20.11.1
      uses: actions/setup-node@v3
      with:
        node-version: 20.11.1
        # cache: 'npm'

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command

    - name: Run build
      uses: borales/actions-yarn@v4
      with:
        cmd: build

      # - name: Test the app
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: run lint # will run `yarn test` command
        
    # - name: Run install
    #   run: npm ci

    # - name: Run Build
    #   run: npm run build --if-present
    # - run: npm test
