name: Build And Test LingLink System

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Use Node.js 20.11.1
      uses: actions/setup-node@v3
      with:
        node-version: 20.11.1
        cache: 'npm'

    - name: Run install
      run: npm ci

    # - name: Run install
    #   uses: borales/actions-yarn@v4
    #   with:
    #     cmd: install # will run `yarn install` command (not working)

    - name: Run build
      uses: borales/actions-yarn@v4
      with:
        cmd: build # will build `yarn build` command

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Test the system
      uses: borales/actions-yarn@v4
      with:
        cmd: test # will run `yarn test` command

    # - name: Test source app
    #   uses: borales/actions-yarn@v4
    #   with:
    #     cmd: run lint # will run `yarn test` command
