name: Deploy LingLink System

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    uses: ./.github/workflows/docker.yaml
    
  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print results
        run: echo "Success"