name: Deploy LingLink System

on:
  workflow_run:
    workflows: ["Build And Push Docker Image with Git"]
    branches: [main]
    types: 
      - completed

jobs:
  docker:
    uses: ./.github/workflows/docker.yaml

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print results
        run: echo "Success"